prompt - create table rights
declare
  v_name varchar2(30 char) := 'RIGHTS';
begin
  for i in (
    select v_name from dual
    minus
    select table_name from user_tables where table_name = v_name
  )
  loop
    execute immediate q'{
      create table rights (
        ri_id           integer            generated by default on null as identity,
        ri_name         varchar2(20 char)  not null,
        ri_description  varchar2(80 char)  ,
        ri_active_yn    char(1)            not null,
        --
        primary key (ri_id),
        unique (ri_name),
        check (ri_active_yn in ('Y', 'N'))
      )
    }';
  end loop;
end;
/
