prompt - create table roles
declare
  v_name varchar2(30 char) := 'ROLES';
begin
  for i in (
    select v_name from dual
    minus
    select table_name from user_tables where table_name = v_name
  )
  loop
    execute immediate q'{
      create table roles (
        ro_id           integer            generated by default on null as identity,
        ro_name         varchar2(20 char)  not null,
        ro_description  varchar2(80 char)  ,
        ro_active_yn    char(1)            not null,
        --
        primary key (ro_id),
        unique (ro_name),
        check (ro_active_yn in ('Y', 'N'))
      )
    }';
  end loop;
end;
/
