declare
  v_name varchar2(30 char) := 'AUTH_RIGHTS';
begin
  for i in (
    select v_name from dual
    minus
    select table_name from user_tables where table_name = v_name
  )
  loop
    execute immediate q'{
      create table auth_rights (
        id           integer            generated by default on null as identity,
        name         varchar2(20 char)  not null,
        description  varchar2(80 char)  ,
        active_yn    char(1)            not null,
        --
        primary key (id),
        unique (name),
        check (active_yn in ('Y', 'N'))
      )
    }';
  end loop;
end;
/
